name: Main

on:
  push:
    tags:
      - '*'

jobs:
  upload-release:
    runs-on: ubuntu-latest
    needs: [build-macos, build-linux, build-windows]
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: uploads
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.AppImage
            *.exe
            *.dmg
  build-macos:
    runs-on: macOS-10.14
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Reconfigure git to use HTTPS authentication
      uses: GuillaumeFalourd/SSH-to-HTTPS@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm ci
    - name: fix token
      uses: datamonsters/replace-action
      with:
        files: 'src\app\app.ts'
        replacements: 'discordClientID: \'\'=${{ secrets.DISCORD_TOKEN }}'
    - name: npm run build
      run: |
        npm run dist-mac
    - name: upload macos artifact
      uses: actions/upload-artifact@v2
      with:
        name: uploads
        path: dist/*.dmg
        if-no-files-found: error
  build-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Reconfigure git to use HTTPS authentication
      uses: GuillaumeFalourd/SSH-to-HTTPS@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm ci
    - name: fix token
      uses: datamonsters/replace-action
      with:
        files: 'src\app\app.ts'
        replacements: 'discordClientID: \'\'=${{ secrets.DISCORD_TOKEN }}'
    - name: npm run build
      run: |
        npm run dist-win
    - name: upload windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: uploads
        path: dist/*.exe
        if-no-files-found: error
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Reconfigure git to use HTTPS authentication
      uses: GuillaumeFalourd/SSH-to-HTTPS@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm ci
    - name: fix token
      uses: datamonsters/replace-action
      with:
        files: 'src\app\app.ts'
        replacements: 'discordClientID: \'\'=${{ secrets.DISCORD_TOKEN }}'
    - name: npm run build
      run: |
        npm run dist-linux
    - name: upload linux artifact
      uses: actions/upload-artifact@v2
      with:
        name: uploads
        path: dist/*.AppImage
        if-no-files-found: error
